"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Siamo sul server PythonAnywhere o in locale? Usato sia per il DB che per la secret key.
IS_PRODUCTION = 'PYTHONANYWHERE_DOMAIN' in os.environ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In produzione DEVE arrivare dalla variabile d'ambiente SECRET_KEY (impostala su
# PythonAnywhere prima di ricaricare l'app, altrimenti l'avvio fallisce con KeyError).
# In locale, se non la imposti, usa un valore di comodo solo per sviluppo.
if IS_PRODUCTION:
    SECRET_KEY = os.environ['SECRET_KEY']
else:
    SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-50s_yk^2b4_)ogu8w9)*q@c$#3_!&u=(0r$8of9&o%)%a!_s_6')

# SECURITY WARNING: don't run with debug turned on in production!
# In produzione DEBUG=True fa accumulare in memoria tutte le query SQL eseguite
# (connection.queries) per l'intera vita del processo worker, rallentando
# progressivamente l'app finche' non viene ricaricata: per questo qui DEVE essere False.
DEBUG = not IS_PRODUCTION

ALLOWED_HOSTS = ['alfredofaro98.pythonanywhere.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MAINTENANCE_MODE = False

SESSION_COOKIE_AGE = 1800  # 30 minuti

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tracker.middleware.MaintenanceModeMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'tracker' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# La password DEVE arrivare dalla variabile d'ambiente DB_PASSWORD in produzione
# (impostala su PythonAnywhere prima di ricaricare l'app, altrimenti KeyError all'avvio).
# In locale, se non la imposti, usa "prova" come prima per comodita'.
if IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'alfredoFaro98$default', # Il nome esatto su PA
            'USER': 'alfredoFaro98',         # Il tuo utente su PA
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': 'alfredoFaro98.mysql.pythonanywhere-services.com',
            'PORT': '3306',
        }
    }
else:
    # Altrimenti, siamo sul tuo PC locale!
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'tracker',              # Il tuo db locale
            'USER': 'root',
            'PASSWORD': os.environ.get('DB_PASSWORD', 'prova'),
            'HOST': '127.0.0.1',
            'PORT': '3306',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'it'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
