from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # Autenticazione (TracerLoginView estende il LoginView built-in per gestire "Ricordami")
    path('', views.TracerLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    
    # App views
    path('dashboard/', views.dashboard, name='dashboard'),
    path('session/create/', views.create_session, name='create_session'),
    path('session/<int:session_id>/', views.session_detail, name='session_detail'),
    path('register/', views.register, name='register'),
    path('set/<int:set_id>/delete/', views.delete_set, name='delete_set'),
    path('set/<int:set_id>/duplicate/', views.duplicate_set, name='duplicate_set'),
    path('set/<int:set_id>/edit/', views.edit_set, name='edit_set'),
    path('session/<int:session_id>/delete/', views.delete_session, name='delete_session'),
    path('session/<int:session_id>/svuota/', views.clear_session, name='clear_session'),
    path('session/<int:session_id>/duplicate/', views.duplicate_session, name='duplicate_session'),
    path('session/<int:session_id>/edit-date/', views.edit_session_date, name='edit_session_date'),
    path('session/<int:session_id>/delete-exercise/<int:exercise_id>/', views.delete_exercise_sets, name='delete_exercise_sets'),
    path('session/<int:session_id>/bulk-delete-sets/', views.bulk_delete_sets, name='bulk_delete_sets'),
    path('session/<int:session_id>/reorder/', views.reorder_exercises, name='reorder_exercises'),
    path('session/<int:session_id>/exercise/<int:exercise_id>/reorder-sets/', views.reorder_sets, name='reorder_sets'),
    path('exercises/', views.exercises_list, name='exercises_list'),

    path('exercises/add/', views.add_exercise, name='add_exercise'),
    path('exercises/add-ajax/', views.add_exercise_ajax, name='add_exercise_ajax'),
    path('exercises/<int:exercise_id>/edit/', views.edit_exercise_admin, name='edit_exercise_admin'),
    path('exercises/<int:exercise_id>/delete/', views.delete_exercise_admin, name='delete_exercise_admin'),
    path('exercises/<int:exercise_id>/images/add/', views.add_exercise_image, name='add_exercise_image'),
    path('exercises/images/<int:image_id>/delete/', views.delete_exercise_image, name='delete_exercise_image'),
    path('exercises/suggestions/', views.exercise_suggestions, name='exercise_suggestions'),
    path('exercises/weight-history/', views.exercise_weight_history, name='exercise_weight_history'),
    path('exercises/export/', views.export_exercises_json, name='export_exercises_json'),
    path('session/<int:session_id>/export/', views.export_session, name='export_session'),
    path('export/', views.export_sessions, name='export_sessions'),
    path('import/', views.import_sessions, name='import_sessions'),
    path('users/', views.user_list, name='user_list'),
    path('users/<str:username>/', views.user_profile, name='user_profile'),
    path('users/<str:username>/session/<int:session_id>/', views.session_view, name='session_view'),
    path('users/<str:username>/session/<int:session_id>/import/', views.import_session_from_user, name='import_session_from_user'),
    path('profile/toggle-visibility/', views.toggle_profile_visibility, name='toggle_profile_visibility'),
    path('body-map/', views.body_map, name='body_map'),
    path('guida/', views.guida, name='guida'),
    path('sessions/week/', views.weekly_sessions_data, name='weekly_sessions_data'),
    path('session/<int:session_id>/circuit/create/', views.create_circuit, name='create_circuit'),
    path('session/<int:session_id>/circuit/import/', views.import_circuit, name='import_circuit'),
    path('circuits/suggestions/', views.circuit_suggestions, name='circuit_suggestions'),
    path('circuit/<int:circuit_id>/edit/', views.edit_circuit, name='edit_circuit'),
    path('circuit/<int:circuit_id>/delete/', views.delete_circuit, name='delete_circuit'),
    path('circuit/<int:circuit_id>/reorder/', views.reorder_circuit_exercises, name='reorder_circuit_exercises'),
    path('circuit/<int:circuit_id>/exercise/<int:exercise_id>/reorder-sets/', views.reorder_circuit_exercise_sets, name='reorder_circuit_exercise_sets'),
    path('water/add/', views.add_water_entry, name='add_water_entry'),
    path('water/add-ajax/', views.add_water_entry_ajax, name='add_water_entry_ajax'),
    path('water/<int:entry_id>/delete/', views.delete_water_entry, name='delete_water_entry'),
    path('water/<int:entry_id>/edit/', views.edit_water_entry, name='edit_water_entry'),
    path('water/goal/', views.set_water_goal, name='set_water_goal'),
    path('water/goal/giorno/', views.set_day_water_goal, name='set_day_water_goal'),
    path('water/storico/', views.water_history, name='water_history'),
    path('integratori/', views.integratori, name='integratori'),
    path('integratori/add/', views.add_integratore_entry, name='add_integratore_entry'),
    path('integratori/<int:entry_id>/delete/', views.delete_integratore_entry, name='delete_integratore_entry'),
    path('integratori/<int:entry_id>/edit/', views.edit_integratore_entry, name='edit_integratore_entry'),
    path('misurazioni/', views.misurazioni, name='misurazioni'),
    path('misurazioni/salva/', views.save_misurazione, name='save_misurazione'),
    path('misurazioni/<int:entry_id>/delete/', views.delete_misurazione, name='delete_misurazione'),
]
