# Generated by Django 5.2.11 on 2026-05-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_workoutset_durata'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='a_cedimento',
            field=models.BooleanField(default=False),
        ),
    ]
