# Generated by Django 5.2.11 on 2026-05-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_a_cedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='barra_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
