# Generated by Django 6.0.2 on 2026-07-28 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_water_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterentry',
            name='creato_il',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
