# Generated by Django 6.0.2 on 2026-07-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_waterentry_creato_il_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='durata_minuti',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='luogo',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='orario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
