# Generated by Django 6.0.2 on 2026-07-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_bodymetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='richiamo',
            field=models.BooleanField(default=False),
        ),
    ]
