# Generated by Django 6.0.2 on 2026-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_workoutset_richiamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='altezza_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='compagni_allenamento',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
