# Generated by Django 6.0.2 on 2026-07-30 07:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_workoutsession_altezza_compagni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('obiettivo_ml', models.PositiveIntegerField()),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('utente', 'data')},
            },
        ),
    ]
