# Generated by Django 6.0.2 on 2026-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_bodymetric_circonferenze'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='carrucole',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
