# Generated by Django 5.2.11 on 2026-08-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_exercise_carrucole'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='external_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions_it',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='origine',
            field=models.CharField(choices=[('personale', 'Personale'), ('opengym', 'openGym')], default='personale', max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='target_muscle',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='exerciseimage',
            name='is_gif',
            field=models.BooleanField(default=False),
        ),
    ]
