# Generated by Django 5.2.11 on 2026-08-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_exercise_external_id_exercise_instructions_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlanOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('riposo', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.tag')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plan_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'data')},
            },
        ),
        migrations.CreateModel(
            name='WeekdayPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno_settimana', models.PositiveSmallIntegerField()),
                ('riposo', models.BooleanField(default=False)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.tag')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'giorno_settimana')},
            },
        ),
    ]
