# Generated by Django 6.0.2 on 2026-08-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_weekdayplan_dayplanoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
