# Generated by Django 6.0.2 on 2026-08-27 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_workoutsession_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='obiettivo_carboidrati_g',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='obiettivo_grassi_g',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='obiettivo_kcal',
            field=models.PositiveIntegerField(default=2200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='obiettivo_proteine_g',
            field=models.PositiveIntegerField(default=140),
        ),
        migrations.CreateModel(
            name='MacroEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.PositiveIntegerField()),
                ('proteine_g', models.PositiveIntegerField(default=0)),
                ('carboidrati_g', models.PositiveIntegerField(default=0)),
                ('grassi_g', models.PositiveIntegerField(default=0)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('creato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-creato_il'],
            },
        ),
    ]
