# Generated by Django 6.0.2 on 2026-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_macroentry_userprofile_obiettivi_macro'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroentry',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
