# Generated by Django 6.0.2 on 2026-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_macroentry_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroentry',
            name='carboidrati_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='macroentry',
            name='grassi_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='macroentry',
            name='proteine_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
