# Generated by Django 6.0.2 on 2026-08-27 12:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_macroentry_grammi_decimali'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('kcal', models.PositiveIntegerField()),
                ('proteine_g', models.PositiveIntegerField(default=0)),
                ('carboidrati_g', models.PositiveIntegerField(default=0)),
                ('grassi_g', models.PositiveIntegerField(default=0)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('utente', 'data')},
            },
        ),
    ]
