# Generated by Django 6.0.2 on 2026-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_macrogoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='carrucole',
        ),
        migrations.AddField(
            model_name='workoutset',
            name='carrucole',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
