# Generated by Django 6.0.2 on 2026-08-27 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_carrucole_da_exercise_a_workoutset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('stato', models.CharField(choices=[('non_tracciato', 'Non tracciato'), ('parziale', 'Tracciato parzialmente')], max_length=20)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macro_day_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente', 'data')},
            },
        ),
    ]
