# Generated by Django 5.2.11 on 2026-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_macrodaystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroentry',
            name='e_spazzatura',
            field=models.BooleanField(default=False),
        ),
    ]
