# Generated by Django 5.2.11 on 2026-08-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0036_macrodaystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent',
            field=models.CharField(choices=[('viola', 'Viola'), ('verde', 'Verde')], default='viola', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tema',
            field=models.CharField(choices=[('scuro_classico', 'Scuro Classico'), ('scuro_ios', 'Scuro (iOS)'), ('chiaro', 'Chiaro')], default='scuro_classico', max_length=20),
        ),
    ]
