# Generated by Django 5.2.11 on 2026-08-30 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0037_macroentry_e_spazzatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('ora_letto', models.TimeField()),
                ('ora_sveglia', models.TimeField()),
                ('qualita', models.CharField(choices=[('scarsa', 'Scarsa'), ('media', 'Media'), ('buona', 'Buona'), ('ottima', 'Ottima')], default='buona', max_length=10)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('creato_il', models.DateTimeField(default=django.utils.timezone.now)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-creato_il'],
            },
        ),
    ]
