# Generated by Django 5.2.11 on 2026-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_userprofile_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='macroentry',
            name='fibre_g',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='macrogoal',
            name='fibre_g',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='obiettivo_fibre_g',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
